Add plotting features for new spin calc modes
perturbo-code/perturbopy pull request #70
Opened 2024-11-26 01:15 UTC by ltan01

Hello,

I added three scripts to plot the outputs for the imsigma_spin, ephmat_spin, and spins calc modes. The imsigma_spin and ephmat_spin scripts are based off of the imsigma and ephmat plotting scripts. The spins plotting script plots the <n|Sigma_z|n> values on the bands, but I tested this using regular norm and LogNorm of (1 - spin value). In this PR, the spins script uses the LogNorm.

Regular norm
![si-spins](https://github.com/user-attachments/assets/3813e8c7-3b19-4f39-b809-b0eb26c4edfa)

Log norm
![si-spins-lognorm](https://github.com/user-attachments/assets/e8936f53-af95-4e77-bfad-dcdbf8f30960)

2024-11-26 08:29 UTC, imaliyov commented
Great work, Laurie! 
Would be great to have these plots (or similar) for the tutorials for this calc mode, perhaps, in this section: https://perturbo-code.github.io/mydoc_scattering.html

Also, are you guys planning to add this mode to PerturboPy? Ideally, all the calc modes implemented in Perturbo should be supported by PerturboPy.

Thank again!

Best,
Ivan

2024-11-26 08:32 UTC, imaliyov commented
Great work, Laurie!

Would be also very nice to have a small tutorial on that on PerturboPy, perhaps here: https://perturbopy.readthedocs.io/en/latest/postproc/tutorials/imsigma.html

Thanks again!

Best,
Ivan

2024-11-26 15:36 UTC, hurricane642 requested changes
That's great work, thank you a lot!
I have comments only on the functions documentation - it should be updated according to the functions parameters and actual purpose of each function. Beside that - great work!

2024-11-26 16:52 UTC, imaliyov commented on src/perturbopy/postproc/calc_modes/ephmat_spin.py
> +        """
Agreed!

2024-11-26 18:56 UTC, ltan01 commented on src/perturbopy/postproc/calc_modes/spins.py
> +        """
The energy_window parameter should still be there for both plot_bands() and plot_spins() in spins.py? I copied functions from bands.py, so the function should be identical

2024-11-26 19:08 UTC, ltan01 commented on src/perturbopy/postproc/calc_modes/ephmat_spin.py
> +    def plot_phdisp(self, ax, show_qpoint_labels=True, **kwargs):
If this function and its parameters are identical to those in the ephmat.py, how should I update the docs? Should I rewrite my scripts so I'm not repeating functions?

2024-11-27 19:03 UTC, ltan01 commented on src/perturbopy/postproc/calc_modes/ephmat_spin.py
> +        """
Added!

2024-11-27 19:03 UTC, ltan01 commented on src/perturbopy/postproc/calc_modes/ephmat_spin.py
> +        """
Added more here!

2024-12-04 09:48 UTC, imaliyov approved these changes

2024-12-04 10:05 UTC, imaliyov commented
We have a conflict with the `src/perturbopy/postproc/calc_modes/ephmat.py` file.
Can we resolve the conflict on this branch, and then merge?

To do this, we have to `git pull origin main`, then resolve and then merge. @hurricane642 correct me if I'm wrong:)

2024-12-04 16:23 UTC, hurricane642 commented
> We have a conflict with the `src/perturbopy/postproc/calc_modes/ephmat.py` file. Can we resolve the conflict on this branch, and then merge?
> 
> To do this, we have to `git pull origin main`, then resolve and then merge. @hurricane642 correct me if I'm wrong:)

That is definitely the funniest conflict I've ever seen...
<img width="162" alt="Снимок экрана 2024-12-04 в 08 21 44" src="https://github.com/user-attachments/assets/48d2cc67-5a53-4fcf-8471-ccc8e41d657e">

Actually, @ltan01 needs to make `rebase` one more time ^^ that is the way to solve the conflicts. Then make `force push` and everything will be resolved:)

2024-12-04 16:36 UTC, ltan01 commented
> > We have a conflict with the `src/perturbopy/postproc/calc_modes/ephmat.py` file. Can we resolve the conflict on this branch, and then merge?
> > To do this, we have to `git pull origin main`, then resolve and then merge. @hurricane642 correct me if I'm wrong:)
> 
> That is definitely the funniest conflict I've ever seen... <img alt="Снимок экрана 2024-12-04 в 08 21 44" width="162" src="https://private-user-images.githubusercontent.com/22166001/392478373-48d2cc67-5a53-4fcf-8471-ccc8e41d657e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzA0MjIsIm5iZiI6MTczMzMzMDEyMiwicGF0aCI6Ii8yMjE2NjAwMS8zOTI0NzgzNzMtNDhkMmNjNjctNWE1My00ZmNmLTg0NzEtY2NjOGU0MWQ2NTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE2MzUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZjk5NWYzNjJlYjI4MjdmNWI4MzQ4MzhkZGU0NDVlOTZjZGEwZGFhNjNlMGYyN2JiZTI5ZTk2MjUyODYyZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aC_N_wBu6dP-5tVNWbDLXXlxzJijMOO45e0V2CDMbsw">
> 
> Actually, @ltan01 needs to make `rebase` one more time ^^ that is the way to solve the conflicts. Then make `force push` and everything will be resolved:)

Haha, yes I’ll take care of the rebase!

2024-12-04 21:33 UTC, hurricane642 commented
Cool, seems like everything is ready. @ltan01 , feel free to merge it whenever you'll be ready!

2024-12-05 02:05 UTC, merged